name: ns-cli
services:
  cli-docker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: cli-docker
    container_name: cli-docker
    volumes:
      - ../:/app
    stdin_open: true
    tty: true
